
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creation du VPC principal de ses sous-reseaux et du VPN
# Initialisation
Parameters:

  VpcCidrBlock:
    Type: String
    MinLength: '9'
    MaxLength: '18'    
    Default: 10.0.0.0/16
    Description: Saisir le réseau du VPC.
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: "Doit être une adresse valide sous la notation : x.x.x.x/x "


Resources:

  P10Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: "aic-projet-10"

# Creation du VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      Tags:
        - Key: Name
          Value: 'P10'
    DependsOn:
      - P10Bucket

