---
## Network preparation for E-Corp's AWS Cloud
# VPC creation
# Creation de trois subnets 
# Creation d'une Internet Gateway
# Creation d'une adresse NAT
# Creation de trois tables de routage 
# association entre les subnets et tables de routage
# Creation de la route par défaut

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creation du VPC principal de ses sous-reseaux et du VPN

# Initialisation
Parameters:

  VpcCidrBlock:
    Type: String
    MinLength: '9'
    MaxLength: '18'    
    Default: 10.0.0.0/16
    Description: Saisir le réseau du VPC.
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: "Doit être une adresse valide sous la notation : x.x.x.x/x "

  PrivateLocalSubnet:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 192.168.1.0/24
    Description: Saisir votre adresse reseau prive. 
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: "Doit etre une IP CIDR valide sous la notation : x.x.x.x/x."

Resources:

  P10Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: PublicRead
      BucketName: "aic-projet-10"

# Creation du VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      Tags:
        - Key: Name
          Value: 'P10'
    DependsOn:
      - P10Bucket

# Creation de 3 sous-reseaux (AZA, AZB et AZC)

  SubnetAZA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Select [10, !Cidr [ !GetAtt myVPC.CidrBlock, 11, 8 ]]
#      CidrBlock: 10.0.10.0/24
      Tags:
        - Key: Name
          Value: 'myVPC-AZA'
      VpcId: !Ref myVPC

  SubnetAZB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Select [20, !Cidr [ !GetAtt myVPC.CidrBlock, 21, 8 ]]
#      CidrBlock: 10.0.20.0/24

      Tags:
        - Key: Name
          Value: 'myVPC-AZB'
      VpcId: !Ref myVPC

  SubnetAZC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 2
          - Fn::GetAZs: !Ref AWS::Region
      CidrBlock: !Select [30, !Cidr [ !GetAtt myVPC.CidrBlock, 31, 8 ]]
#      CidrBlock: 10.0.30.0/24
      Tags:
        - Key: Name
          Value: 'myVPC-AZC'
      VpcId: !Ref myVPC

# Creation de la passerelle Internet 
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: 'InternetGateway-${AWS::StackName}'
  AttachInternetGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref InternetGateway

# Creation de l'interface NAT
  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGatewayAZC:
    DependsOn: AttachInternetGateway
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref SubnetAZC
      Tags:
        - Key: Name
          Value: !Sub NAT-${AWS::StackName}

# Creation de 3 tables de routage + Association
  # AZA
  RouteTableAZA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Route-AZA-${AWS::StackName}

  AttachRouteTableAZA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableAZA
      SubnetId: !Ref SubnetAZA

  # AZB
  RouteTableAZB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Route-AZB-${AWS::StackName}

  AttachRouteTableAZB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableAZB
      SubnetId: !Ref SubnetAZB

  # AZC
  RouteTableAZC:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: Route-AZC-${AWS::StackName}

  AttachRouteTableAZC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTableAZC
      SubnetId: !Ref SubnetAZC

# Creation des Routes par défaut
  # AZA
  RouteAZA:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTableAZA

  # AZB
  RouteAZB:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTableAZB

  # AZC
  RouteAZC:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGatewayAZC
      RouteTableId: !Ref RouteTableAZC
 
 
Outputs:

  AZASubnetCidr:
    Description: AZA's CIDR Subnet block
    Value: !Select [10, !Cidr [ !GetAtt myVPC.CidrBlock, 11, 8 ]]
#    Value: 10.0.10.0/24
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZACidr ] ]

  AZBSubnetCidr:
    Description: AZB's CIDR Subnet block
    Value: !Select [20, !Cidr [ !GetAtt myVPC.CidrBlock, 21, 8 ]]
#    Value: 10.0.20.0/24
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZBCidr ] ]

  AZCSubnetCidr:
    Description: AZC's CIDR Subnet block
    Value: !Select [30, !Cidr [ !GetAtt myVPC.CidrBlock, 31, 8 ]]
#    Value: 10.0.30.0/24
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZCCidr ] ]

  SubnetAZAId:
    Description: The AZA's Subnet ID
    Value: !Ref SubnetAZA
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZAId ] ]

  SubnetAZBId:
    Description: The AZB's Subnet ID
    Value: !Ref SubnetAZB
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZBId ] ]

  SubnetAZCId:
    Description: The AZC's Subnet ID
    Value: !Ref SubnetAZC
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", SubnetAZCId ] ]

  AddressEIP:
    Description: Elastic IP Address
    Value: !Ref NatEip
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", NatEipId ] ]


  LocalSubnetCidr:
    Description: Local Subnet Cidr Block 
    Value: !Ref PrivateLocalSubnet
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", LocalSubnetCidr ] ]

  RouteTableAZA:
    Description: The AZA's Route ID
    Value: !Ref RouteTableAZA
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", RouteTableAZAid ] ]
  RouteTableAZB:
    Description: The AZB's Route ID
    Value: !Ref RouteTableAZB
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", RouteTableAZBid ] ]
  RouteTableAZC:
    Description: The AZC's Route ID
    Value: !Ref RouteTableAZC
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", RouteTableAZCid ] ]
  
  Gateway:
    Description: Gateway Address
    Value: !Ref   InternetGateway
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", InternetGatewayId ] ]
