AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Managed VPN with BGP

Parameters:
  CustomerIP:
    Type: String
    MinLength: '7'
    MaxLength: '15'
    Default : 176.136.96.14
    Description: Saisir l'adresse ip publique
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})'
    ConstraintDescription: "Doit etre une IP CIDR valide sous la notation : x.x.x.x"

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: Selectioner le VPC du projet

  InstanceAMI:
    Description: OpenVPN AMI
    Type: String
    Default: ami-bc3566ab

  InstanceType:
    Description: OpenVPN Instance Type
    Type: String
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    Default: t2.micro

  KeyName:
    Description: SSH Key Name
    Type: AWS::EC2::KeyPair::KeyName

  AdminPassword:
    Description: OpenVPN Admin Password
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 32
    ConstraintDescription: Must be at least 8 chars long

  RouteAllTraffic:
    Description: Should all local traffic go over VPN when connected?
    Type: Number
    AllowedValues:
      - 0
      - 1
    Default: 1

  UseVPNDNS:
    Description: Should client use VPN supplied DNS when connected?
    Type: Number
    AllowedValues:
      - 0
      - 1
    Default: 1
